export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB  to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it I praticed many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the project, I had have this unique and complex webshop app. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript','Stripe'],
    source: 'https://github.com/D3troit98/ecommerce-demo.git',
    visit: 'https://ecommerce-54edcd.netlify.app',
    id: 1,
  },
  {
    title: 'Youtube Web App',
    description: "This is a youtube webappp that makes use of youtube API to show embeded youtube videos.While building it I learnt the youtube API calls and other peices of information found in the object. Got even more familiar with material-ui and it was fun playing my favorite artist.",
      image: '/images/5.png',
      tags: ['React', 'Youtube','Material-UI'],
    source: 'https://github.com/D3troit98/youtube-react-app.git',
    visit: 'https://quiet-youtube-viewer-683e53.netlify.app',
    id: 2,
  },
  {
    title: 'Expense Tracker',
    description: "A budget tracking application made with material-ui, react-chartjs-2 and uuid. Making use of React and Speechly.Speechly is fun and exicting as it makes an application powered by your voice. You get to store information just by speaking with your application",
    image: '/images/6.png',
    tags: ['React', 'Speechly','Material-UI'],
    source: 'https://github.com/D3troit98/react-expense-tracker.git',
    visit: 'https://voice-expenser-6e257c.netlify.app/',
    id: 3,
  },
  {
    title: 'Article Landing Page',
    description: "A full responsive React Website that works well in different screen sizes. Building this landing page was interesting as it's CSS property was gotten using figma;By following the figma design layout. Did some excellent file/folder structure and its sections can easily be updated.",
    image: '/images/7.png',
    tags: ['React', 'Figma'],
    source: 'https://github.com/D3troit98/ai-react-article.git',
    visit: 'https://ai-article-8c22ab.netlify.app',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Worked as a freelance developer', },
  { year: 2020, text: 'Built C++ Applications', },
  { year: 2021, text: 'Shared my projects with the world', },
  { year: 2022, text: 'Moved into React', },
];